package com.sociogo.dashboard;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import com.jfoenix.controls.JFXDrawer;
import com.jfoenix.controls.JFXHamburger;
import com.jfoenix.transitions.hamburger.HamburgerBackArrowBasicTransition;
import com.sociogo.fblogin.FacebookLoginController;
import com.sociogo.login.LoginController;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.VBox;

public class DashboardController implements Initializable
{
	public static String first_name;
	
	@FXML
    private JFXDrawer drawer;
	
	@FXML
	private JFXHamburger hamburger;
	
	@FXML
	private Label sociogo;
	
	@FXML
	public Label fname;

	// Event Listener on MenuItem.onAction
	@FXML
	public void viewProfile(ActionEvent event)
	{
		// TODO Autogenerated
	}
	
	// Event Listener on MenuItem.onAction
	@FXML
	public void logoutHandle(ActionEvent event)
	{
		// TODO Autogenerated
	}
	
	@Override
	public void initialize(URL location, ResourceBundle resources)
	{
		try
		{
			Image icon = new Image(getClass().getResourceAsStream("/com/sociogo/icons/sociogo.png"));
			sociogo.setGraphic(new ImageView(icon));
			if(FacebookLoginController.fname == null)
			{
				fname.setText(LoginController.fname);
			}
			else
			{
				fname.setText(FacebookLoginController.fname);
			}
			first_name = fname.getText();
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
		try
		{
			VBox box = FXMLLoader.load(getClass().getResource("/com/sociogo/drawer/Drawer.fxml"));
			drawer.setSidePane(box);
			HamburgerBackArrowBasicTransition transition = new HamburgerBackArrowBasicTransition(hamburger);
			transition.setRate(-1);
			hamburger.addEventHandler(MouseEvent.MOUSE_PRESSED, (e) ->
			{
				transition.setRate(transition.getRate() * -1);
				transition.play();
				if(drawer.isShown())
				{
					drawer.close();
				}
				else
				{
					drawer.open();
				}
			});
		}
		catch (IOException e1)
		{
			e1.printStackTrace();
		}
	}
}
